name: QT Windows Build

on: [push]

jobs:
  build:
    runs-on: windows-latest # 仅在 Windows 上运行
    strategy:
      fail-fast: false
    name: Windows Build
    steps:
      - name: Git checkout
        uses: actions/checkout@v3 # 拉取代码

      - name: Install Qt for Windows # 安装 Qt
        uses: jurplel/install-qt-action@v3
        with:
          version: '5.15.2'
          arch: 'win64_mingw'
          
      - name: Set PATH for Qt tools
        run: echo "C:\Qt\5.15.2\mingw81_64\bin" >> $GITHUB_PATH

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2 # 安装 MinGW
        with:
          platform: x64

      - name: Compile using MinGW
        shell: cmd
        run: |
          mingw32-make

      - name: Pack Windows executable # 打包应用
        run: |
          mkdir app
          cp release/class-manager.exe app/
          windeployqt app/class-manager.exe
