name: QT
on: [push]
jobs:
  build:
    runs-on: ${{ matrix.os }}#运行平台
    strategy:
      matrix:
        os: [windows-latest]
      fail-fast: false
    name: ${{ matrix.os }}
    steps:
    - name: Git checkout
      uses: actions/checkout@v3#拉取代码
    - name: Install Qt windows #安装Qt
      if: matrix.os == 'windows-latest'
      uses: jurplel/install-qt-action@v3
      with:
        version: '5.15.2'
        arch: 'win64_mingw'
    - name: Set up MinGW
      if: matrix.os == 'windows-latest'
      uses: egor-tensin/setup-mingw@v2#安装windows的MinGW
      with:
          platform: x64
    - name: compile make win
      if: matrix.os == 'windows-latest'
      shell: cmd
      run: |
        mingw32-make
    - name: pack win exe #复制
      if: matrix.os == 'windows-latest'
      run: |
        mkdir app
        cp release/class-manager.exe app
        cd app
        windeployqt class-manager.exe
